FROM iregistry.baidu-int.com/baidu-base/python:3.10-noble

RUN apt update && apt install -y --no-install-recommends \
    zip net-tools less psmisc python3-pip pkg-config \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages --no-cache-dir poetry

WORKDIR /home/work/

COPY --chown=work:work hugegraph-python-client/ ./hugegraph-python-client/
COPY --chown=work:work hugegraph-llm/ ./hugegraph-llm/

RUN cd /home/work/hugegraph-llm && \
    poetry config virtualenvs.in-project true && \
    poetry lock && \
    poetry install --no-interaction --no-ansi --verbose

ENV PATH="/home/work/hugegraph-llm/.venv/bin:$PATH"

WORKDIR /home/work/hugegraph-llm

USER work

CMD [ "python", "-m", "hugegraph_llm.demo.rag_demo.app", "--port", "8080" ]